version: "3"

services:
  backend:
    image: vanshv/backend-crm
    ports:
      - "3001:3001"
    depends_on:
      - mongo_db
      - redis_cache

  frontend:
    image: vanshv/frontend-crm
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo_db:
    image: mongo
    restart: always
    volumes:
      - mongo_db:/data/db

  redis_cache:
    image: redis
    restart: always
    volumes:
      - redis_cache:/data/db

volumes: 
  mongo_db: {}
  redis_cache: {}