version: "3"

services:
  backend:
    # build: ./client-api
    image: vanshv/backend-crm
    ports:
      - "3001:3001"
    # environment:
    #   MONGO_URL: mongodb://mongo_db:27017/crmvs_db
    #   REDIS_URL: redis://redis_cache:6379
    #   JWT_ACCESS_SECRET: helloredis1232fhowe
    #   JWT_REFRESH_SECRET: hellodbf428rq9j
    #   JWT_REFRESH_SECRET_EXP_DAY: 30
    # hello ji
    depends_on:
      - mongo_db
      - redis_cache

  frontend:
    # build: ./crmv-frontend
    image: vanshv/frontend-crm
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo_db:
    image: mongo
    restart: always
    volumes:
      - mongo_db:/data/db

  redis_cache:
    image: redis
    restart: always
    volumes:
      - redis_cache:/data/db

volumes: 
  mongo_db: {}
  redis_cache: {}