---
- name: Run Playbook
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Get All Images and Build
      command: docker compose build
    - name: Run Services
      command: docker compose up -d