---
- name: run it all idk
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull frontend image
      docker_image:
        name: vanshv/frontend-crm:latest
        source: pull
    - name: Pull backend image
      docker_image:
        name: vanshv/backend-crm:latest
        source: pull
    - name: Stop docker compose
      command: sudo docker compose down
    - name: Get All Images and Build
      command: sudo docker compose build
    - name: Run Services
      command: sudo docker compose up -d