### User sign up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name": "vanshv",
    "company": "none",
    "address": "Kalka",
    "phone": 1234567890,
    "email": "vanshvsa123@gmail.com",
    "password": "vanshvsa123"
}

### User sign in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
    "email": "vanshvsa123@gmail.com",
    "password": "vanshvsa123"
}

### Get a user profile endpoint
GET  http://localhost:3001/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZhbnNodnNhMTIzQGdtYWlsLmNvbSIsImlhdCI6MTcwMjEyMTg1NSwiZXhwIjoxNzAyMTIyNzU1fQ.sF0KcK0yAeiN1gnlOhoRx-WNmWtIGKwhUFX6-sRu8JM

###Token routers

### Get refreshed token
GET http://localhost:3001/v1/tokens
Authorization: ###Token routers

### Get refreshed token
GET http://localhost:3001/v1/tokens
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZhbnNodnNhMTIzQGdtYWlsLmNvbSIsImlhdCI6MTcwMjEyMTg1NSwiZXhwIjoxNzA0NzEzODU1fQ.5oIEYTqYQ0u6UKicMjiuVbm8wswKRqkiCXf0p_NjDuw



//bugs

//does not invalidate duplicate emailid requests
//i can set this in mongosh wtih 
//db.users.createIndex({email:1}, {unique:true})
//need to do this everytime mongosh is opened

//refreshJWT field token not added, 
//even through addedAt is added, token field is empty

# {
#   "status": "success",
#   "message": "Login Successful",
#   "accessJWT": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZhbnNodnNhMTIzQGdtYWlsLmNvbSIsImlhdCI6MTcwMjEyMTg1NSwiZXhwIjoxNzAyMTIyNzU1fQ.sF0KcK0yAeiN1gnlOhoRx-WNmWtIGKwhUFX6-sRu8JM",
#   "refreshJWT": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZhbnNodnNhMTIzQGdtYWlsLmNvbSIsImlhdCI6MTcwMjEyMTg1NSwiZXhwIjoxNzA0NzEzODU1fQ.5oIEYTqYQ0u6UKicMjiuVbm8wswKRqkiCXf0p_NjDuw"
# }
